import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/fonts";
import Header from "@/layouts/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
